GET http://localhost:8080/api/posts

###

GET http://localhost:8080/api/posts/1

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
    "title": "Post",
    "content": "Content"
}

###

PUT http://localhost:8080/api/posts/5
Content-Type: application/json

{
    "id":"5",
    "title": "Post updated",
    "content": "Content updated"
}

###

DELETE http://localhost:8080/api/posts/26
