version: '3.8'
name: posts-api-ecosystem
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-php

  api-php:
    build:
      context: .
    volumes:
      - ./app:/var/www/html/app
      - ./public:/var/www/html/public
      - ./messaging:/var/www/html/messaging
      - ./logger:/var/www/html/logger
      - ./composer.json:/var/www/html/composer.json
      - .env:/var/www/html/.env
    depends_on:
      - db
      - rabbitmq
      - elasticsearch

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672" # RabbitMQ Web Panel
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - discovery.type=single-node
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    ports:
      - "5601:5601" # Kibana web interface
    depends_on:
      - elasticsearch

volumes:
  rabbitmq_data:
  db_data:
  es_data: